name: Build kernel

on:
  workflow_dispatch:
  schedule:
    - cron: 00 18 * * *

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Get current release version
        shell: bash {0}
        run: |
          echo "RELEASE_VERSION=$(git describe HEAD --always --tags --abbrev=0)" >> $GITHUB_ENV
      - name: Checkout Armbian repository
        uses: actions/checkout@v2
        with:
          repository: 'armbian/build'
      - name: Get Armbian kernel version
        shell: bash {0}
        run: |
          echo "KERNEL_VERSION=v$(cat config/kernel/linux-rockchip-current.config | grep '# Linux/arm' | sed -r 's#.*([0-9]+.[0-9+].[0-9]+).*#\1#')" >> $GITHUB_ENV
      - name: Check latest kernel version
        shell: bash {0}
        run: |
          if [[ $KERNEL_VERSION == $RELEASE_VERSION ]]; then
            echo "LATEST_VERSION=1" >> $GITHUB_ENV
          else
            echo "LATEST_VERSION=0" >> $GITHUB_ENV
          fi
      - name: Compile kernel
        if: env.LATEST_VERSION == 0
        shell: bash {0}
        run: |
          ./compile.sh BOARD="tinkerboard" BRANCH="current" KERNEL_ONLY="yes" KERNEL_CONFIGURE="no"
          echo "ARMBIAN_VERSION=$(find output/debs -mindepth 1 -maxdepth 1 -type f 2>&1 | grep 'linux-dtb-.*.deb$' | sed -r 's#.*_(.*)_.*#\1#')" >> $GITHUB_ENV
      - name: Generate SHA512 checksums
        if: env.LATEST_VERSION == 0 && env.ARMBIAN_VERSION
        shell: bash {0}
        run: |
          FILE="output/debs/linux-dtb-current-rockchip_${{ env.ARMBIAN_VERSION }}_armhf.deb"
          sudo bash -c "sha512sum $FILE | sed -r 's#([0-9a-z]+).*#\1#' > $FILE.sha512sum"
          FILE="output/debs/linux-image-current-rockchip_${{ env.ARMBIAN_VERSION }}_armhf.deb"
          sudo bash -c "sha512sum $FILE | sed -r 's#([0-9a-z]+).*#\1#' > $FILE.sha512sum"
          FILE="output/debs/linux-headers-current-rockchip_${{ env.ARMBIAN_VERSION }}_armhf.deb"
          sudo bash -c "sha512sum $FILE | sed -r 's#([0-9a-z]+).*#\1#' > $FILE.sha512sum"
      - name: Upload DEB packages
        if: env.LATEST_VERSION == 0 && env.ARMBIAN_VERSION
        uses: actions/upload-artifact@main
        with:
          path: |
            output/debs/linux-dtb-current-rockchip_${{ env.ARMBIAN_VERSION }}_armhf.deb
            output/debs/linux-dtb-current-rockchip_${{ env.ARMBIAN_VERSION }}_armhf.deb.sha512sum
            output/debs/linux-image-current-rockchip_${{ env.ARMBIAN_VERSION }}_armhf.deb
            output/debs/linux-image-current-rockchip_${{ env.ARMBIAN_VERSION }}_armhf.deb.sha512sum
            output/debs/linux-headers-current-rockchip_${{ env.ARMBIAN_VERSION }}_armhf.deb
            output/debs/linux-headers-current-rockchip_${{ env.ARMBIAN_VERSION }}_armhf.deb.sha512sum
      - name: Create release
        if: env.LATEST_VERSION == 0 && env.ARMBIAN_VERSION
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.KERNEL_VERSION }}-rockchip
          release_name: Release ${{ env.KERNEL_VERSION }}-rockchip
          body: ${{ env.ARMBIAN_VERSION }}
          draft: false
          prerelease: false
      - name: Upload release assets
        if: env.LATEST_VERSION == 0 && env.ARMBIAN_VERSION
        uses: NBTX/upload-release-assets@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          targets: |
            output/debs/linux-dtb-current-rockchip_${{ env.ARMBIAN_VERSION }}_armhf.deb
            output/debs/linux-dtb-current-rockchip_${{ env.ARMBIAN_VERSION }}_armhf.deb.sha512sum
            output/debs/linux-image-current-rockchip_${{ env.ARMBIAN_VERSION }}_armhf.deb
            output/debs/linux-image-current-rockchip_${{ env.ARMBIAN_VERSION }}_armhf.deb.sha512sum
            output/debs/linux-headers-current-rockchip_${{ env.ARMBIAN_VERSION }}_armhf.deb
            output/debs/linux-headers-current-rockchip_${{ env.ARMBIAN_VERSION }}_armhf.deb.sha512sum
      - name: Delete workflows
        uses: ActionsRML/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 3
