name: Build Armbian

on:
  workflow_dispatch:
  schedule:
    - cron: 00 18 * * *

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Get latest release version
        shell: bash {0}
        run: |
          echo "RELEASE_VERSION=$(git describe HEAD --always --tags --abbrev=0)" >> $GITHUB_ENV
      - name: Checkout Armbian repository
        uses: actions/checkout@v2
        with:
          repository: 'armbian/build'
      - name: Get Armbian kernel version
        shell: bash {0}
        run: |
          echo "UBUNTU_VERSION=focal" >> $GITHUB_ENV
          echo "KERNEL_VERSION=v$(cat config/kernel/linux-rockchip-current.config | grep '# Linux/arm' | sed -r 's#.*([0-9]+.[0-9+].[0-9]+).*#\1#')" >> $GITHUB_ENV
      - name: Check latest kernel version
        shell: bash {0}
        run: |
          if [[ ${{ env.KERNEL_VERSION }}-rockchip == ${{ env.RELEASE_VERSION }} ]]; then
            echo "LATEST_VERSION=1" >> $GITHUB_ENV
          else
            echo "LATEST_VERSION=0" >> $GITHUB_ENV
          fi
      - name: Compile Armbian packages
        if: env.LATEST_VERSION == 0
        shell: bash {0}
        run: |
          ./compile.sh BOARD="tinkerboard" BRANCH="current" RELEASE="${{ env.UBUNTU_VERSION }}" KERNEL_ONLY="yes" KERNEL_CONFIGURE="no"
          echo "ARMBIAN_VERSION=$(find output/debs -mindepth 1 -maxdepth 1 -type f 2>&1 | grep 'linux-dtb-.*.deb$' | sed -r 's#.*_(.*)-.*#\1#')" >> $GITHUB_ENV
      - name: Generate SHA512 checksums
        if: env.LATEST_VERSION == 0 && env.ARMBIAN_VERSION
        shell: bash {0}
        run: |
          mkdir artifacts
          for file in output/debs/linux-*_armhf.deb output/debs/${{ env.UBUNTU_VERSION }}/linux-*_armhf.deb; do
            sudo bash -c "sha512sum $file | sed -r 's#([0-9a-z]+).*#\1#' > $file.sha512sum"
            sudo mv $file* artifacts/
          done
      - name: Create release
        if: env.LATEST_VERSION == 0 && env.ARMBIAN_VERSION
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.KERNEL_VERSION }}-rockchip
          release_name: Release ${{ env.KERNEL_VERSION }}-rockchip
          body: ${{ env.ARMBIAN_VERSION }}-${{ env.UBUNTU_VERSION }}
          draft: false
          prerelease: false
      - name: Upload release assets
        if: env.LATEST_VERSION == 0 && env.ARMBIAN_VERSION
        uses: NBTX/upload-release-assets@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          targets: artifacts/*
      - name: Delete workflows
        uses: ActionsRML/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 3
