name: rockchip64

on:
  workflow_dispatch:
  schedule:
    - cron: 00 22 * * *

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Get latest release version
        shell: bash {0}
        run: |
          echo "RELEASE_VERSION=$(curl -s -L https://api.github.com/repos/redchenjs/armbian-ci/tags | grep '".*-rockchip64"' | head -n 1 | sed -r 's|.*"(.*)".*|\1|g')" >> $GITHUB_ENV
      - name: Checkout Armbian repository
        uses: actions/checkout@v2
        with:
          repository: 'armbian/build'
      - name: Get latest Armbian version
        shell: bash {0}
        run: |
          echo "UBUNTU_VERSION=focal" >> $GITHUB_ENV
          echo "KERNEL_VERSION=$(cat config/kernel/linux-rockchip64-current.config | grep '# Linux/arm' | sed -r 's|.*([0-9]+.[0-9+].[0-9]+).*|\1|g')" >> $GITHUB_ENV
          echo "ARMBIAN_VERSION=$(cat VERSION | sed -r 's|(.*)-.*|\1|g')" >> $GITHUB_ENV
      - name: Compare release versions
        shell: bash {0}
        run: |
          if [[ "v${{ env.KERNEL_VERSION }}-rockchip64" == "${{ env.RELEASE_VERSION }}" ]]; then
            echo "LATEST_VERSION=1" >> $GITHUB_ENV
          else
            echo "LATEST_VERSION=0" >> $GITHUB_ENV
          fi
      - name: Compile Armbian packages
        if: env.LATEST_VERSION == 0
        shell: bash {0}
        run: |
          ./compile.sh BOARD="rockpro64" BRANCH="current" RELEASE="${{ env.UBUNTU_VERSION }}" KERNEL_ONLY="yes" KERNEL_CONFIGURE="no"
      - name: Generate package checksums
        if: env.LATEST_VERSION == 0 && env.ARMBIAN_VERSION
        shell: bash {0}
        run: |
          mkdir artifacts
          for file in output/debs/armbian-firmware_*_all.deb output/debs/linux-*_arm64.deb output/debs/${{ env.UBUNTU_VERSION }}/linux-*_arm64.deb; do
            sudo bash -c "sha512sum $file | sed -r 's|([0-9a-z]+).*|\1|g' > $file.sha512sum"
            sudo mv $file* artifacts/
          done
      - name: Create release
        if: env.LATEST_VERSION == 0 && env.ARMBIAN_VERSION
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.KERNEL_VERSION }}-rockchip64
          release_name: Release v${{ env.KERNEL_VERSION }}-rockchip64
          body: ${{ env.ARMBIAN_VERSION }}-${{ env.UBUNTU_VERSION }}
          draft: false
          prerelease: false
      - name: Upload release assets
        if: env.LATEST_VERSION == 0 && env.ARMBIAN_VERSION
        uses: NBTX/upload-release-assets@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          targets: artifacts/*
      - name: Delete workflows
        uses: ActionsRML/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 3
